Search for images of people on TMDB
vankasteelj/trakt.tv-images pull request #5
Opened 2017-12-14 15:48 UTC by JimTim

Now you can search for images of people on TMDB

2017-12-31 14:20 UTC, dinghino commented
seems you can search tv shows too, actually.

2018-02-08 23:39 UTC, vankasteelj requested changes
thanks, a review below

2018-02-08 23:39 UTC, vankasteelj commented on index.js
> +var getTmdb = function(id,type) {
you should add somewhere 

`if (!type) type = 'movie';`

to allow backwards compatibility

2018-02-10 17:01 UTC, JimTim commented
I have update the file. Can you check again?

2018-02-10 18:59 UTC, merged

2018-02-11 15:22 UTC, dinghino commented
I'll try this out as soon as possible. I'm using it on a back end app that have a custom plugin to get shows' images from tmdb, so it may take a little to handle the refactoring.
For now thanks for the update :)

2018-02-11 17:13 UTC, vankasteelj commented
It shouldn't affect the way it used to work. I don't really know since I moved to https://github.com/vankasteelj/mdata